---
- hosts: all
  connection: netconf
  gather_facts: no
  vars:
    #device_username: 'nc-admin'
    #device_password: 'supersecret'
    ansible_network_os: junos

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 5

    - name: "Load a configuration from a Jinja2 template and commit"
      junos_config:
        update: "replace"
        src: "../templates/junos/user.j2"
        src_format: "text"
        confirm: 5
      register: response

    - name: confirm previous commit
      junos_config:
        confirm_commit: yes